### ISSUE TITLE
投币似乎出现问题

### ISSUE THREAD

**Issue by zzcabc** [srcrs/BilibiliTask#140]
发现时间再2月6日,感觉是获取投币uid问题,但是我检查yml文件感觉并未出错
config.yml文件
```
#每天需要投币的数量 [0,5]。
coin: 5
#送出即将过期礼物 [true,false]
gift: true
#银瓜子兑换为硬币 [true,false]
s2c: true
#月底自动使用B币卷 [{0,自己会使用},{1,给自己充电},{2,兑换成金瓜子}]
autoBiCoin: 1
#用户设备的标识 [android,ios]
platform: android
#自定义优先给这些 up 的视频投币 , 以yml数组的形式 , 填写其 uid (mid)
upList: 
  - 487550002
  - 521070071
  - 508963009
  - 623441612
  - 1612112
#进行漫画签到任务 [true,false]
manga: true
#优先送出即将过期礼物给此up的直播间,填写其 uid
upLive: 21811136
#对于进行投币的视频选择是否点赞 , 默认不点赞 [0,1]
selectLike: 1
```

错误日志
```
java.lang.NullPointerException: null
	at top.srcrs.task.daily.ThrowCoinTask.getTodayUpList(ThrowCoinTask.java:253)
	at top.srcrs.task.daily.ThrowCoinTask.run(ThrowCoinTask.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at top.srcrs.BiliStart.lambda$scanTask$0(BiliStart.java:110)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at top.srcrs.BiliStart.scanTask(BiliStart.java:105)
	at top.srcrs.BiliStart.main(BiliStart.java:44)
```

**Comment by srcrs** [comment]
```java
        JSONArray vList = getThrowCoinVideoList();
        List<String> configUpList = config.getUpList();
        List<String> upList = new ArrayList<>();
        for (Object object : vList) {         // 253行
```
我估计是获取近30天投币视频列表为空，您的账号近期是否投过币？

**Comment by srcrs** [comment]
@zzcabc 你更新一下最新代码，看解决了没有

**Comment by zzcabc** [comment]
已经可以投币,之前一直用这个项目
